feat(yarn): add support for yarn berry + artifactory
blackboard-innersource/gh-action-setup-artifactory pull request #6
Opened 2021-10-07 21:25 UTC by justinm

This PR adds support for Yarn 2 Berry which has deviated from using ~/.npmrc in preference of its own format via ~/.yarnrc.yml. The resulting .yamlrc.yml should look something like:

```
npmRegistries:
  //blackboard.jfrog.io/artifactory/api/npm/fnds-npm/:
    npmAlwaysAuth: true
    npmAuthIdent: ${ARTIFACTORY_IDENT}

npmScopes:
  bb-fnds:
    npmRegistryServer: "https://blackboard.jfrog.io/artifactory/api/npm/fnds-npm"
  lct:
    npmRegistryServer: "https://blackboard.jfrog.io/artifactory/api/npm/fnds-npm"
```

2021-10-07 21:44 UTC, robinverduijn requested changes

2021-10-07 21:44 UTC, robinverduijn commented on setup_yarn.sh
> +
You'll likely want to do `set -e` so that any unexpected failures do properly fail the script instead of silently continuing.

2021-10-08 00:41 UTC, richarivers approved these changes

2021-10-08 17:53 UTC, polothy commented
I'd probably want to see some tests.  Bash testing can be a little wild, so I can maybe add them at some point.

Readme also need updating.  We probably need to be specific on what version of yarn this works with?  IDK if we need to rename to `setup_yarn_v2.sh` or something?

2021-10-12 01:33 UTC, ftclausen commented
> I'd probably want to see some tests. Bash testing can be a little wild, so I can maybe add them at some point.
> 
> Readme also need updating. We probably need to be specific on what version of yarn this works with? IDK if we need to rename to `setup_yarn_v2.sh` or something?

There are some Bash unit test framework such as [shunit2](https://github.com/kward/shunit2)

2021-10-12 01:35 UTC, ftclausen approved these changes

2021-10-25 21:29 UTC, polothy requested changes
I was trying to get this ready to merge by writing tests for it, but started to find some potential issues that I don't have time to figure out.  So, I left a bunch of comments instead.

If you can please try to write tests, that would be super helpful in getting this merged.  Example: https://github.com/blackboard-innersource/gh-action-setup-artifactory/blob/c9b46bac7c43f3105bebc31ef3daf7ce9338c187/test/setup_npm.bats

To run tests, just do `make test`

2021-10-25 21:29 UTC, polothy commented on setup_yarn.sh
> +    echo "Skipping npm setup because ARTIFACTORY_SETUP_NPM=$ARTIFACTORY_SETUP_NPM"
```suggestion
  if [ "$ARTIFACTORY_SETUP_YARN" == "false" ]; then
    echo "Skipping yarn setup because ARTIFACTORY_SETUP_YARN=$ARTIFACTORY_SETUP_YARN"
```
Should be toggled by its own variable.

2021-10-25 21:29 UTC, polothy commented on setup_yarn.sh
> +  lines+=("  //${configKey}:")
```suggestion
  lines+=("  ${ARTIFACTORY_NPM_REGISTRY}:")
```

From the docs, we can put the protocol here, so I'd just assume do that

2021-10-25 21:29 UTC, polothy commented on setup_yarn.sh
> +  configKey=${ARTIFACTORY_NPM_REGISTRY#"https://"}
```suggestion
```
Remove, see below.

2021-10-25 21:29 UTC, polothy commented on setup_yarn.sh
> +  local npmrc
```suggestion
```
Unused.

2021-10-25 21:29 UTC, polothy commented on setup_yarn.sh
> +  local registry
```suggestion
```
Unused.

2021-10-25 21:29 UTC, polothy commented on setup_yarn.sh
> +  local configKey
```suggestion
```
Will be unused, see below.

2021-10-25 21:29 UTC, polothy commented on setup_yarn.sh
> +  ident=$(encode "$ARTIFACTORY_USERNAME:$ARTIFACTORY_TOKEN")
Are you sure this should be encoded? Docs don't mention it: https://yarnpkg.com/configuration/yarnrc#npmAuthIdent

2021-10-25 21:29 UTC, polothy commented on setup_yarn.sh
> +      lines+=("  $scope:")
It looks like scopes should omit the `@` in the config: https://yarnpkg.com/configuration/yarnrc#npmScopes

Example value of `$ARTIFACTORY_NPM_SCOPES` is `"@scope1,@scope2"`

2021-10-25 21:34 UTC, robinverduijn commented
> I was trying to get this ready to merge by writing tests for it, but started to find some potential issues that I don't have time to figure out. So, I left a bunch of comments instead.
> 
> If you can please try to write tests, that would be super helpful in getting this merged. Example: https://github.com/blackboard-innersource/gh-action-setup-artifactory/blob/c9b46bac7c43f3105bebc31ef3daf7ce9338c187/test/setup_npm.bats
> 
> To run tests, just do `make test`

(Starting a new message here because Github doesn't allow threading on "normal" comments)

What kind of file extension is `.bats`?

2021-10-25 21:50 UTC, polothy commented
It's from this: https://github.com/bats-core/bats-core

2022-11-03 09:15 UTC, frichtarik commented
already implemented in #9

2022-11-03 09:15 UTC, closed without merging